# Generated by Django 2.2.6 on 2019-10-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_en', models.CharField(max_length=50)),
                ('audience', models.IntegerField()),
                ('open_data', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('watch_grade', models.CharField(max_length=50)),
                ('poster_url', models.CharField(max_length=200)),
                ('score', models.FloatField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
